name: Bump version
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Bump version and push tag
        uses: TriPSs/conventional-changelog-action@v3.1.1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          git-message: 'chore(release): {version}'
          output-file: 'CHANGELOG.md'
